export const MENUS = [
  {
    name: 'Dashboard',
    path: '/dashboard',
    icon: 'Dashboard',
    level: 1,
    parent_id: 0,
    sort: 1,
    is_group: 0,
  },
  {
    name: 'Maintaince',
    path: '',
    icon: 'Maintaince',
    level: 1,
    parent_id: 0,
    sort: 2,
    is_group: 1,
  },
  {
    name: 'User',
    path: '/maintaince/user',
    icon: '',
    level: 2,
    parent_id: 2,
    sort: 1,
    is_group: 0,
  },
  {
    name: 'Role',
    path: '/maintaince/role',
    icon: '',
    level: 2,
    parent_id: 2,
    sort: 2,
    is_group: 0,
  },
  {
    name: 'Role Menu',
    path: '/maintaince/role-menu',
    icon: '',
    level: 2,
    parent_id: 2,
    sort: 3,
    is_group: 0,
  },
  {
    name: 'Master Setup',
    path: '',
    icon: 'Setup',
    level: 1,
    parent_id: 0,
    sort: 3,
    is_group: 1,
  },
  {
    name: 'Banner',
    path: '/master-setup/banner',
    icon: '',
    level: 2,
    parent_id: 6,
    sort: 1,
    is_group: 0,
  },
  {
    name: 'Contact',
    path: '/master-setup/contact',
    icon: '',
    level: 2,
    parent_id: 6,
    sort: 2,
    is_group: 0,
  },
  {
    name: 'Master',
    path: '',
    icon: 'Master',
    level: 1,
    parent_id: 0,
    sort: 4,
    is_group: 1,
  },
  {
    name: 'Artist',
    path: '/master/artist',
    icon: '',
    level: 2,
    parent_id: 9,
    sort: 1,
    is_group: 0,
  },
  {
    name: 'Article',
    path: '/master/article',
    icon: '',
    level: 2,
    parent_id: 9,
    sort: 2,
    is_group: 0,
  },
  {
    name: 'Exhibition',
    path: '/master/exhibition',
    icon: '',
    level: 2,
    parent_id: 9,
    sort: 3,
    is_group: 0,
  },
  {
    name: 'Master Product',
    path: '',
    icon: 'Product',
    level: 1,
    parent_id: 0,
    sort: 5,
    is_group: 1,
  },
  {
    name: 'Category',
    path: '/master-product/category',
    icon: '',
    level: 2,
    parent_id: 13,
    sort: 1,
    is_group: 0,
  },
  {
    name: 'Sub Category',
    path: '/master-product/sub-category',
    icon: '',
    level: 2,
    parent_id: 13,
    sort: 2,
    is_group: 0,
  },
  {
    name: 'Theme',
    path: '/master-product/theme',
    icon: '',
    level: 2,
    parent_id: 13,
    sort: 3,
    is_group: 0,
  },
  {
    name: 'Product',
    path: '/master-product/product',
    icon: '',
    level: 2,
    parent_id: 13,
    sort: 4,
    is_group: 0,
  },
  {
    name: 'Order',
    path: '',
    icon: 'Order',
    level: 1,
    parent_id: 0,
    sort: 6,
    is_group: 1,
  },
  {
    name: 'Order List',
    path: '/order/order-list',
    icon: '',
    level: 2,
    parent_id: 18,
    sort: 1,
    is_group: 0,
  },
];
